# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e00d06aaed7419d96581ae550dcd17b732b78301e69c18e6bbfe8c3f7771fa6dd97dd713387fe05000cbfcef046835db8c976382fb06551783eea080b4f163e

test:
  secret_key_base: 0f106ef45662685acb61ae114c1f1e1398aa90d1cbbd5e934f7bb03e48fdd0d1340b28618dd8dfa178007f7c6953da2e069abc231117b34ec9c0a726229e19f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
